name: Test Model

on:
  workflow_dispatch:

jobs:
  test-model:
    name: Test the Model
    runs-on: self-hosted
    container:
      image: pytorch/pytorch
      options: --user root
    steps:
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: traffic_sign_net
          run-id: 13714691477
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install dependencies
      #   run: | 
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      - name: Run testing script
        run: python scripts/test_model.py --model traffic_sign_net.pth
