name: Train Model

on:
  workflow_dispatch:

jobs:
  train-model:
    name: Train the Model
    runs-on: self-hosted
    container:
      # image: ubuntu:latest 
      image: pytorch/pytorch
      options: --user root
    steps:
      # - name: Set up Python
      #  run: | 
      #    apt update
      #    apt -y upgrade
      #    apt -y install python3 python3-pip python-is-python3 python3-venv
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Install dependencies
      #  run: | 
      #    python -m venv .venv
      #    . .venv/bin/activate
      #    pip install -r requirements.txt
      - name: Run training script
        run: python scripts/train_model.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: traffic_sign_net
          path: ${{ github.workspace }}/models/traffic_sign_net.pth
          retention-days: 5
